version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: face_recognition_db
    environment:
      POSTGRES_DB: face_recognition
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - face_recognition_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres_test:
    image: pgvector/pgvector:pg16
    container_name: face_recognition_db_test
    environment:
      POSTGRES_DB: face_recognition_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  face_recognition_db_data: